import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { gql, useQuery } from "@apollo/client";
import { Game } from "../types";

const FEED_QUERY = gql`
  {
    feed {
      id
      title
      description
      createdAt
      updatedAt
      user {
        name
        id
        image
      }
    }
  }
`;

const Home: NextPage = () => {
  const { data, loading, error } = useQuery(FEED_QUERY);

  if (error) console.error(error);

  const { feed } = data || {};

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && <p>Loading...</p>}
      <ul>
        {feed?.map((game: Game) => (
          <li key={game.id}>{game.title}</li>
        ))}
      </ul>
    </div>
  );
};

export default Home;
