import { useState } from "react";
import { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { gql, useQuery } from "@apollo/client";
import { useSession } from "next-auth/client";
import NewUserDialog from "../components/users/NewUserDialog";
import { Query } from "../generated/graphql";

const FEED_QUERY = gql`
  {
    feed {
      id
      title
      description
      createdAt
      updatedAt
      user {
        name
        id
        image
      }
    }
  }
`;

const Home: NextPage = () => {
  const [session] = useSession();
  // Setting this in state so it can be passed as the 'open' prop to FirstSessionDialog
  // and can also be used to handle the close event.
  const [isFirstSession, setIsFirstSession] = useState(
    session?.isNewUser as boolean
  );
  const { data, loading, error } = useQuery<Query>(FEED_QUERY);

  if (error) console.error(error);

  const { feed } = data || {};

  const handleFirstSessionDialogClose = () => {
    setIsFirstSession(false);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && <p>Loading...</p>}
      {isFirstSession && (
        <NewUserDialog
          open={isFirstSession}
          handleClose={handleFirstSessionDialogClose}
        />
      )}
      <ul>
        {feed?.map((game) => (
          <li key={game.id}>{game.title}</li>
        ))}
      </ul>
    </div>
  );
};

export default Home;
